image: python:3.6-slim

pages:
  stage: deploy
  tags:
  - shell
  script:
  - pip install .
  - cd docs
  - pip install -r requirements.txt
  - python3 -m sphinx.cmd.build -M html "source" "build" 
  - cp source/my_theme.css build/html/_static/css
  - cp -r build/html/ ../public
  artifacts:
    paths:
    - public
  only:
  - master
